version: '3'
services:
  web:
    image: teklifimgelsin1_web
    container_name: 7a011bd8bd88
    restart: always
    volumes:
      - .:/app
    expose:
      - "8000"  # Flask uygulaması için expose
    command: gunicorn -w 4 -b 0.0.0.0:8000 app:app

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Nginx yapılandırması
    depends_on:
      - web
